# Generated by Django 5.2.7 on 2025-11-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="customer_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="delivered_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="order_day",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="product_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
