# Generated by Django 5.2.7 on 2025-11-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_record_customer_response_record_delivered_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
