# Generated by Django 5.2.7 on 2025-11-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_record_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="rating",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
