# Generated by Django 5.2.7 on 2025-11-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_record_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="rating",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
