# Generated by Django 5.2.8 on 2026-01-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffee",
            name="email",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
